set(AXR_VERSION_MAJOR 0)
set(AXR_VERSION_MINOR 4)
set(AXR_VERSION_PATCH 9)
set(AXR_VERSION_BUILD 0)
set(AXR_VERSION_STRING "${AXR_VERSION_MAJOR}.${AXR_VERSION_MINOR}")

if(AXR_VERSION_BUILD GREATER 0)
    set(AXR_VERSION_STRING "${AXR_VERSION_STRING}.${AXR_VERSION_PATCH}.${AXR_VERSION_BUILD}")
elseif(AXR_VERSION_PATCH GREATER 0)
    set(AXR_VERSION_STRING "${AXR_VERSION_STRING}.${AXR_VERSION_PATCH}")
endif()

# Numeric-only version string; i.e. 1.0.7.3
set(AXR_VERSION_STRING_REAL ${AXR_VERSION_STRING})

# TODO: Re-enable git tags when this mess is sorted out
# Human-readable version string; i.e. 1.0.8-beta1
# git_append_shorttag(AXR_VERSION_STRING)

set(AXR_VENDOR "AXR Project Contributors")
set(AXR_DOMAIN "axrproject.org")
set(AXR_CONTACT "info@axrproject.org")
set(AXR_WEB_URL "http://${AXR_DOMAIN}/")

set(AXR_README_FILE "${CMAKE_SOURCE_DIR}/README.md")
set(AXR_LICENSE_FILE "${CMAKE_SOURCE_DIR}/LICENSE")

set(AXR_README_FILE_TXT "${CMAKE_BINARY_DIR}/README.txt")
set(AXR_LICENSE_FILE_TXT "${CMAKE_BINARY_DIR}/LICENSE.txt")

set(AXR_README_FILE_RTF "${CMAKE_BINARY_DIR}/README.rtf")
if(PANDOC)
    execute_process(COMMAND ${PANDOC} -s -o "${AXR_README_FILE_RTF}" "${AXR_README_FILE}")
endif()
