set(AXR_VERSION_MAJOR 0)
set(AXR_VERSION_MINOR 4)
set(AXR_VERSION_PATCH 7)
set(AXR_VERSION_BUILD 0)
set(AXR_VERSION_STRING "${AXR_VERSION_MAJOR}.${AXR_VERSION_MINOR}")

if(AXR_VERSION_BUILD GREATER 0)
    set(AXR_VERSION_STRING "${AXR_VERSION_STRING}.${AXR_VERSION_PATCH}.${AXR_VERSION_BUILD}")
elseif(AXR_VERSION_PATCH GREATER 0)
    set(AXR_VERSION_STRING "${AXR_VERSION_STRING}.${AXR_VERSION_PATCH}")
endif()

git_append_shorttag(AXR_VERSION_STRING)

set(AXR_VENDOR "AXR Project Contributors")
set(AXR_DOMAIN "axr.vg")
set(AXR_CONTACT "info@axr.vg")

set(AXR_README_FILE "${CMAKE_SOURCE_DIR}/README.md")
set(AXR_LICENSE_FILE "${CMAKE_SOURCE_DIR}/LICENSE")

set(AXR_README_FILE_TXT "${CMAKE_BINARY_DIR}/README.txt")
set(AXR_LICENSE_FILE_TXT "${CMAKE_BINARY_DIR}/LICENSE.txt")
